export const ErrorCodes = {
  INVALID_REQUEST: "INVALID_REQUEST",
  SESSION_NOT_FOUND: "SESSION_NOT_FOUND",
  TURN_ALREADY_RUNNING: "TURN_ALREADY_RUNNING",
  IDEMPOTENCY_CONFLICT: "IDEMPOTENCY_CONFLICT",
  CONFIG_VALUE_INVALID: "CONFIG_VALUE_INVALID",
  RATE_LIMITED: "RATE_LIMITED",
  PROMPT_EXEC_FAILED: "PROMPT_EXEC_FAILED",
  ACP_PROTOCOL_ERROR: "ACP_PROTOCOL_ERROR",
  ACP_PROCESS_UNAVAILABLE: "ACP_PROCESS_UNAVAILABLE",
  ACP_INIT_TIMEOUT: "ACP_INIT_TIMEOUT",
  NO_ACTIVE_TURN: "NO_ACTIVE_TURN",
  SESSION_CLOSE_FAILED: "SESSION_CLOSE_FAILED",
  SESSION_NOT_READY: "SESSION_NOT_READY",
  STORE_WRITE_FAILED: "STORE_WRITE_FAILED",
  DESIGN_GATE_FAILED: "DESIGN_GATE_FAILED",
  PLANNING_GATE_FAILED: "PLANNING_GATE_FAILED",
  WORKFLOW_NOT_FOUND: "WORKFLOW_NOT_FOUND",
  WORKFLOW_INVALID_TRANSITION: "WORKFLOW_INVALID_TRANSITION"
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
